version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - 8080:8080
  database:
    image: mongo
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 27017:27017
