version: '3.4'

services:
  api:
    build: .
    # volumes:
    #   - ./:/node-app
    #   - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - database
    links:
      - database
    ports:
      - 8080:8080
  database:
    image: mongo
    # volumes:
    #   - ./data/db:/data/db
    ports:
      - 27017:27017
